---
layout: post
title: "Clase 13"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: |
  Distribuciones de probabilidad continuas: </br>
  - Distribución Uniforme continua. </br>
  - Distribución Gamma. </br>
  - Distribución Exponencial. </br>
  &nbsp * Propiedad de carencia de memoria.  <br/>
  &nbsp * Relación con la distribución Poisson.
  
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase13"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```

## Distribuciones de probabilidad continuas
### Distribución Uniforme continua
Se dice que la variable aleatoria `$X$` tiene una distribución uniforme continua, definida en el intervalo `$(a,b)$`, si su función de probabilidad está dada por
`\begin{align*}
f(x) = \begin{cases} \frac{1}{b-a} \quad \quad & a\leq x\leq b \\
0 \quad \quad & \text{en otro caso}\end{cases}
\end{align*}`

### Teorema
Si `$X\sim Unif(a,b)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X) = \frac{b+a}{2} \quad \quad Var(X)=\frac{(b-a)^2}{12}
\end{align*}`

### Teorema
Si `$X\sim Unif(a,b)$`, entonces se puede probar que la función de distribución acumulada de la variable aleatoria `$X$` es de la forma
`\begin{align*}
F(x) = \frac{x-a}{b-a} \quad \quad & a\leq x\leq b 
\end{align*}`

### Función Gamma
La función gamma se define como
`\begin{align*}
\Gamma(\alpha) = \int^\infty_0 t^{\alpha-1}e^{-t} dt
\end{align*}`

### Propiedades función Gamma
<ol type = "a">
<li> $\Gamma(\alpha) = (\alpha-1)\Gamma(\alpha)$, para todo $\alpha>0$ </li>
<li> $\Gamma(n) = (n-1)!$, siendo $n$ un entero positivo. </li>
<li> $\Gamma(1/2) = \sqrt{\pi}$ </li>
</ol>

### Distribución Gamma
Se dice que la variable aleatoria `$X$` tiene una distribución Gamma con parámetro de forma `$\alpha$` y de escala `$\beta$`, si su función de densidad de probabilidad está dada por
`\begin{align*}
f(x) = \begin{cases} \frac{1}{\Gamma(\alpha)\beta^\alpha} x^{\alpha-1}e^{-{\frac{x}{\beta}}} \quad \quad & x>0; \alpha>0; \beta>0 \\
0 \quad \quad & \text{en otro caso}\end{cases}
\end{align*}`

### Teorema
Si `$X\sim Gamma(\alpha,\beta)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X) = \alpha\beta \quad \quad Var(X)=\alpha\beta^2
\end{align*}`

### Distribución Exponencial
Se dice que la variable aleatoria `$X$` tiene una distribución Exponencial con parámetro de escala `$\beta$`, si su función de densidad de probabilidad está dada por
`\begin{align*}
f(x) = \begin{cases} \frac{1}{\beta} e^{-{\frac{x}{\beta}}} \quad \quad & x>0; \beta>0 \\
0 \quad \quad & \text{en otro caso}\end{cases}
\end{align*}`
en donde se observa que ésta distribución es un caso particular de la distribución Gamma cuando `$\alpha=1$`.

### Teorema
Si `$X\sim Exp(\beta)$`, entonces se puede probar que la media y varianza de la variable aleatoria `$X$` están dadas por
`\begin{align*}
\mathbb{E}(X) = \beta \quad \quad Var(X)=\beta^2
\end{align*}`

### Teorema
Si `$X\sim Exp(\beta)$`, entonces se puede probar que la función de distribución acumulada de la variable aleatoria `$X$` es de la forma
`\begin{align*}
F(x) =  1 - e^{-{\frac{x}{\beta}}} \quad \quad & x>0; \beta>0
\end{align*}`

## Propiedad de carencia de memoria
Suponga que `$X$` es una variable aleatoria tal que `$X\sim Exp(\beta)$`, entonces sean dos reales positivos `$a$` y `$b$`, entonces se puede probar que

1. `$\mathbb{P}(X\geq a+b | x \geq b) = \mathbb{P}(X\geq a)$` 
2. `$\mathbb{P}(X\leq a+b | x \geq b) = \mathbb{P}(X\leq a)$`

## Relación entre la distribución Exponencial y el proceso Poisson
Suponga que el número de eventos que ocurren en un intervalo de tiempo `$t$`, tiene una distribución Poisson con parámetro `$\lambda$` y que el número ocurrencias en intervalos de tiempo distintos son independientes entre si. Entonces se tendrá que la distribución del tiempo transcurrido entre dos eventos de Poisson sucesivos es Exponencial con parámetro `$\beta = \frac{t}{\lambda}$`.