---
layout: post
title: "Clase 05"
main-class: 'clase'
permalink: /EstadisticaI/EstI:title.html
tags:

introduction: |
              Tecnicas de conteo. <br>
              - Regla multiplicativa <br>
              - Permutación de n objetos <br>
              - Permutación de n objetos tomados de a r <br>
              - Permutación en circulo <br>
              - Permutación por clases <br>
              - Combinatoria <br>
              - Combinatoria por subconjuntos <br>
              - Permutaciones o Combinatorias?
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../EstadisticaI/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../EstadisticaI/images/", "Clase05"),
               cache.path = "../../EstadisticaI/cache/",
               cache = FALSE)

```


## Técnicas de conteo
Las técnicas de conteo son una serie de métodos de matemáticos usados para **contar el número de arreglos posibles** dentro de uno o varios conjuntos de eventos. 
La razón del empleo de las técnicas de conteo se debe a que en muchos casos es necesario resolver un problema de probabilidad mediante el conteo del número de puntos en un espacio muestral, sin listar realmente cada uno de los elementos perteneciente a un evento determinado.

### Regla multiplicativa
**Si una operación consiste en `$k$` diferentes pasos**, donde el primer paso puede realizarse de `$n_1$` formas distintas, el segundo paso puede realizarse de `$n_2$` formas distintas, `$\ldots$` y el `$i$`-ésimo paso puede realizarse de `$n_i$` formas distintas, con `$i=1,2,\ldots,k$`, entonces la operación completa se puede realizar de `$(n_1)(n_2)(n_3)\ldots(n_k)$` formas distintas.

#### Ejercicio

1. Suponga que en un grupo de Estadística I hay un total de `$10$` hombres y `$7$` mujeres, de cuantas formas posibles puede el profesor escoger un hombre y luego una mujer para que resuelvan un ejercicio?
2. Cuantos números impares de 2 dígitos pueden formarse con el conjunto de números `$1,3,4,2,6,0,9,8$` si cada uno de ellos sólo puede ser seleccionado una sola vez?

<button id="Show1" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide1" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito1"> 
<h3 data-toc-skip> Solución </h3> 
<ol type ="1">
<li>Como hay un total de $n_1=10$ foras de seleccionar un hombre y $n_2=7$ formas de seleccionar una mujer, entonces el número de formas de seleccionar un hombre y luego una mujer es de 
$$\begin{align*}
n_1\times n_2 = (10)(7) = 70 \text{ formas}
\end{align*}$$
</li>
<li> Como el número puede ser impar, entonces el <strong>número posibilidades asociadas a las unidades</strong> debe terminar en $1,3 \text{ o } 9$, lo cual da un total de $n_1=3$ posibilidades. <br>

Por su parte, el <strong>número asociado a las decenas</strong>, puede tomar cualquier valor de los posibles, es decir, $1,3,4,2,6,0,9,8$ <strong>restringido al números seleccionado en las unidades</strong>, entonces el número de posibilidades para las decenas será de $n_2=7$ posibilidades. <br>

Entonces el número de posibilidades de armar números pares con el conjunto de números $1,3,4,2,6,0,9,8$ es de
$$\begin{align*}
n_1\times n_2 = (3)(7) = 21 \text{ posibilidades}
\end{align*}$$
</li>
</ol>
</main>

### Permutación de `$n$` objetos
Para cualquier número entero no negativo `$n$`, se tiene que el número de permutaciones o arreglos **ordenados** de `$n$` objetos diferentes es `$n!$`
`\begin{align*}
n! &= n(n-1)! \\
n! &= n(n-1)(n-2)! \\
n! &= n(n-1)(n-2)\ldots(3)(2)(1) \\
\end{align*}`
donde el caso especial de `$0!=1$`

#### Ejercicio
Suponga que en el curso de Estadística I hay un total de `$8$` estudiantes que van a presentar un supletorio, de cuantas formas puede organizar el profesor los estudiantes en una fila?

<button id="Show2" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide2" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito2"> 
<h3 data-toc-skip> Solución </h3> 
<p> Como hay un total de $8$ estudiantes, entonces el total de formas en que el profesor puede ordenar el total de estudiantes en una fila es, $8$ posibles estudiantes en el primer puesto, $7$ posibles estudiantes en el segundo puesto, $\ldots$, y $1$ posible estudiante en el último puesto. Esto es,
$$\begin{align*}
8! = 8\times7\times6\times5\times4\times3\times2\times1=40320 \text{ formas}
\end{align*}$$
</p>
</main>

### Permutación de `$n$` objetos tomados de a `$r$`
Similarmente, el número de formas de ordenar `$n$` objetos diferentes tomados de `$r$` objetos a la vez estará dado por
`\begin{align*}
_nP_r= n(n-1)(n-2)\ldots(n-r+1)=\frac{n!}{(n-r)!}\\
\end{align*}`
donde en el caso especial de `$n=r$`, se tendrá la formula
`\begin{align*}
_nP_n= \frac{n!}{(n-n)!}=\frac{n!}{0!}=n!\\
\end{align*}`

#### Ejercicio
Suponga que en la facultad de Ciencias Económicas se encuentran en elecciones, y se van a seleccionar `$4$` profesores para cubrir los puestos de Decano, Vicedecano, Jefe del departamento de Economía y Jefe del departamento de Administración de Empresas. Si se tiene un total de `$25$` candidatos, de cuantas maneras se pueden llenar estos `$4$` puestos.

<button id="Show3" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide3" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito3"> 
<h3 data-toc-skip> Solución </h3> 
<p> Como hay un total de $25$ aspirantes, entonces se tendrán $25$ posibilidades para ocupar el puesto de Decano, $24$ posibilidades para ocupar el puesto de Vicedecano dado que se ocupó ya el primer puesto, $23$ posibilidades para ocupar el puesto de Jefe del departamento de Economía dado que ya se ocuparon los dos primeros puestos, y $22$ posibilidades para ocupar el puesto de Jefe del departamento de Administración de Empresas dado que ya se ocuparon los tres primeros puestos. Esto es
$$\begin{align*}
25\times24\times23\times22=303600 \text{ formas}
\end{align*}$$

Lo anterior es equivalente al obtenido usando el teorema de permutación de $n$ objetos tomados de a $r$, en donde, se tiene un total de $n=25$ aspirantes, para los cuales se les asignará un total de $r=4$ puestos, dando como resultado
$$\begin{align*}
_{25}P_4 = \frac{25!}{(25-4)!} = 303600 \text{ formas}
\end{align*}$$
  </p>
</main>


### Permutación en circulo
El número de permutaciones de `$n$` objetos ordenados en forma circular es de `$(n-1)!$`. Dos permutaciones circulares no se consideran diferentes a menos
que los objetos correspondientes en los dos arreglos estén precedidos o seguidos por un objeto diferente.

#### Ejercicio
De cuantas manera puede organizar el profesor de Estadística I a `$6$` estudiantes (Andrés, Ana, Luisa, Camila, Sebastián, Pedro) en una mesa redonda para resolver un trabajo, si

1. No hay ninguna restricción.
2. Si Luisa y Camila deben sentarse juntas.
3. Si Luisa y Camila no pueden sentarse juntos.

<button id="Show4" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide4" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito4"> 
<h3 data-toc-skip> Solución </h3> 
<ol type="1">
<li> Cuando no hay restricción, se tendrá entonces que dejando uno de los estudiantes en un punto fijo, el profesor podrá sentar a los estudiantes en una mesa redonda de
$$\begin{align*}
(6-1)! = 120 \text{ formas}
\end{align*}$$
</li>
<li> Cuando hay una restricción, la idea es tratar de encontrar el número de ordenes posibles de la restricción y luego el número de ordenes en total. Como la restricción es que Luisa y Camila deben sentarse juntas, entonces, se tendrá 
$$2!=2$$

formas diferentes de sentar a Luisa y a Camila (primero Luisa y luego Camila, o primero Camila y luego Luisa), una ves resuelto esto, <strong>se toman estas dos personas como si fueran un solo individuo</strong>, dejando un total de $5$ grupos (uno con Camila y Luisa, y los otros individuales) sin restricción para sentar en la mesa redonda. <br>

Dejando a uno de los grupos en un punto fijo, el profesor tendrá un total de
$$\begin{align*}
(5-1)! = 24 \text{ formas}
\end{align*}$$
de sentar en un mesa redonda a los $5$ grupos. Ahora, si tenemos en cuenta la restricción anteriormente calculada, entonces se tendrá que el profesor podrá sentar a los $6$ estudiantes en una mesa redonda, con Luisa y Camila juntas de
$$\begin{align*}
2 * 24 = 48 \text{ formas}
\end{align*}$$
</li>
<li> Similar al punto anterior, solo que en este caso la idea es encontrar el número de formas en donde Luisa y Camila no se sienten juntas. Si seguimos el proceso del inciso anterior, tendremos que en $24$ formas de las $120$ totales, Luisa y Camila estarán sentadas juntas, eso quiere decir que el profesor podrá sentar a los $6$ estudiantes en una mesa redonda, con Luisa y Camila separadas de 
$$\begin{align*}
120 - 24 = 96 \text{ formas}
\end{align*}$$
</li>
</ol>
</main>

### Permutación por clases
El número de permutaciones distintas en `$n$` objetos, en los que `$n_1$` objetos son de una clase, `$n_2$` objetos de una segunda clase, `$\ldots$`, y `$n_k$` objetos de una `$k$`-ésima clase es
`\begin{align*}
\frac{n!}{n_1! n_2! \ldots n_k!}
\end{align*}`
donde `$n=n_1+n_2+\ldots+n_k$`

#### Ejercicio

En la facultad de Ciencias Económicas están interesados de armar un equipo de fútbol y para ello necesitan inscribir `$15$` jugadores. Entre los cuales se inscriben `$3$` de primer semestre, `$5$` de segundo semestre, `$2$` de tercer semestre, `$1$` de cuarto semestre, `$2$` de quinto semestre, `$1$` de octavo semestre y `$1$` de décimo semestre. Si al finalizar el torneo el equipo de Ciencias Económicas queda de segundo y para la entrega de medallas se desea entregarlas por semestre al que pertenecen los estudiantes. De cuantas formas diferentes pueden ordenarse los `$15$` jugadores para recibir las medallas, si solo importa el semestre en el que pertenecen?

<button id="Show5" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide5" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito5"> 
<h3 data-toc-skip> Solución </h3>
<p>Dado que solo importa el semestre al que pertenecen los `$15$` estudiantes, entonces se tendrán un total de `$7$` clases, entre las cuales, la primera posee `$3$` estudiantes, la segunda posee `$5$` estudiantes, la tercera posee `$2$` estudiantes, la cuarta posee `$1$` estudiante, la quinta posee `$2$` estudiantes, la sexta posee `$1$` estudiante y la séptima posee `$1$` estudiante. 
Por tanto, para entregar las medallas, el número de arreglos diferentes que pueden formarse son
$$\begin{align*}
\frac{15!}{3!\;5!\;2!\;1!\;2!\;1!\;1!} = \frac{1307674368000}{2880} = 454053600 \text{ formas}
\end{align*}$$
</p>
</main>

### Combinatoria
El número de combinaciones de `$n$` objetos, tomando `$r$` objetos a la vez, es el número de subconjuntos de tamaño `$r$`, que se pueden formar a partir de los `$n$` objetos en los cuales **el orden no importa**. Entonces, el número de subconjuntos **desordenados** de tamaño `$r$` escogidos **sin reemplazo**, de un total de `$n$` objetos disponibles es
`\begin{align*}
_nC_r=\left(\begin{array}{c}n\\ r\end{array}\right) = \frac{n!}{r! (n-r)!}
\end{align*}`
en donde puede observarse que
`\begin{align*}
_nC_r=\frac{_nP_r}{r!}
\end{align*}`
y en consecuencia `$_nC_r < _nP_r$`

#### Ejercicio
Suponga que entre el total de `$27$` estudiantes que están en el curso de Estadística I, el profesor decide seleccionar `$4$` para que realicen un quiz sorpresa. De cuantas maneras puede el profesor escoger un grupo de `$4$` personas del total de estudiantes del curso?

<button id="Show6" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide6" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito6"> 
<h3 data-toc-skip> Solución </h3> 
Dado que no importa el orden en el cual el estudiante sea escogido va a tener que presentar el quiz y un estudiante no puede ser seleccionado más de una vez, se tiene que el total de estudiantes $n=27$, mientras que el total de estudiantes que tomará son $r=4$, entonces se tendrá que el número de formas en que el profesor puede hacer la selección es
$$\begin{align*}
_{27}C_{4}= \frac{27!}{4! (27-4)!} = 17550 \text{ formas}
\end{align*}$$
</main>

### Combinatoria por subconjuntos
El número de maneras en que un conjunto de `$n$` objetos diferentes se puede dividir o partir en `$k$` subconjuntos de `$n_1$` objetos el primer subconjunto, `$n_2$` objetos el segundo subconjunto, `$\ldots$`, y `$n_k$` objetos el `$k$`-ésimo subconjunto es
`\begin{align*}
\left(\begin{array}{c}n\\ n_1, n_2, \ldots, n_k\end{array}\right) = \frac{n!}{n_1!\;n_2!\;\ldots\;n_k!}
\end{align*}`

siendo `$\sum_{i=1}^kn_i=n$`.

#### Ejercicio
Suponga que un grupo de `$10$` estudiantes del grupo de Estadística I asisten a un congreso y deciden hospedarse en un hostal. Si una hay dos habitación triple, una doble y dos privadas, de cuantas formas pueden repartirse los estudiantes?

<button id="Show7" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide7" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito7"> 
El número de formas posibles en que pueden repartirse los $10$ estudiantes, siendo $n_1=3$ y $n_2=3$ las dos habitaciones triples, $n_3=2$ la habitaciones doble y $n_4=1$ y $n_5=1$ las dos habitaciones privadas, entonces
$$\begin{align*}
\left(\begin{array}{c}10\\ 3, 3, 2, 1, 1\end{array}\right) = \frac{10!}{3!\;3!\;2!\;1!\;1!} = 50400 \text{ formas}
\end{align*}$$
</main>

### Permutaciones o Combinatorias?
Con el proposito de identificar cuando se deben usar permutaciones y cuando se deben usar combinatorias, es necesario determinar si **el conteo se realiza con reemplazo o sin reemplazo**, y además determinar si **los objetos se encuentran o no ordenados**. Entonces, suponga que se tienen `$n$` objetos de los cuales se desean tomar `$r$` a la vez, entonces planteamos los siguientes `$4$` escenarios

#### Caso 1: Con orden, sin reemplazo
`\begin{align*}
_nP_r= n(n-1)(n-2)\ldots(n-r+1)=\frac{n!}{(n-r)!}
\end{align*}`

#### Caso 2: Con orden, con reemplazo
`\begin{align*}
n^r
\end{align*}`

#### Caso 3: Sin orden, sin reemplazo
`\begin{align*}
_nC_r = \left(\begin{array}{c}n\\ r\end{array}\right) = \frac{n!}{r!\;(n-r)!}
\end{align*}`

#### Caso 4: sin orden con reemplazo
`\begin{align*}
_{n+r-1}C_r = \left(\begin{array}{c}n+r-1\\ r\end{array}\right) = \frac{(n+r-1)!}{r!\;(n-1)!}
\end{align*}`

#### Ejercicio
Suponga que se está interesado en jugar una lotería, en la cual deben seleccionarse `$4$` diferentes números. De cuantas formas es posible seleccionar estos `$4$` números

1. Si en la lotería influye el orden y los números deben seleccionarse sin reemplazo.
2. Si en la lotería influye el orden y los números pueden seleccionarse con reemplazo.
3. Si en la lotería no influye el orden y los números deen seleccionarse sin reemplazo.
4. Si en la lotería no influye el orden y los números pueden seleccionarse con reemplazo.

<button id="Show8" class="btn btn-secondary">Mostrar Solución </button>
<button id="Hide8" class="btn btn-info">Ocultar Solución </button>
<main id="botoncito8"> 
<ol type ="1">
<li>Dado que <strong>influye el orden</strong> de los números y <strong>no se puede seleccionar un número dos veces</strong>, se tiene que el total números de $4$ dígitos que se pueden formar son
$$\begin{align*}
_{10}P_4= \frac{10!}{(10-4)!} = 5040 \text{ números}
\end{align*}$$
</li>
<li>Dado que <strong>influye el orden</strong> de los números y <strong>se posible seleccionar un número más de una vez</strong>, se tiene que el total de números de $4$ dígitos que se pueden formar son
$$\begin{align*}
10^4 = 10000 \text{ números}
\end{align*}$$
</li>
<li>Dado que <strong>no influye el orden</strong> de los números y <strong>no se puede seleccionar un número dos veces</strong>, se tiene que el total números de $4$ dígitos que se pueden formar son
$$\begin{align*}
_{10}C_4= \frac{10!}{4!\;(10-4)!} = 210 \text{ números}
\end{align*}$$
</li>
<li>Dado que <strong>no influye el orden</strong> de los números y <strong>se posible seleccionar un número más de una vez</strong>, se tiene que el total de números de $4$ dígitos que se pueden formar son
$$\begin{align*}
_{10+4-1}C_4 = \frac{(10+4-1)!}{4!\;(10-1)!} = 715 \text{ números}
\end{align*}$$
</li>
</ol>
</main>
