---
layout: post
title: "Clase 08"
main-class: 'clase'
permalink: /ProbabilidadeInferencia/PeIE:title.html
tags:

introduction: |
  Funciones de probabilidad continuas. <br/>
  Función de distribución acumulada. <br/>
  Esperanza matemática y varianza.
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../ProbabilidadeInferencia/_posts/", output_format = "all")})
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../ProbabilidadeInferencia/images/", "Clase08"),
               cache.path = "../../ProbabilidadeInferencia/cache/",
               cache = FALSE)

```

## Funciones de probabilidad continuas

Se dice que la función `$f(x)$` es una función de densidad de probabilidad (*fdp*) de la variable aleatoria continua `$X$`, definida en el conjunto de números reales si

1. `$f(x)\geq0$` para todo `$x \in \mathbb{R}$`
2. `$\int_{-\infty}^\infty f(x) dx=1$`
3. `$\int_{a}^b f(x) dx=\mathbb P(a<X<b)$`

## Función de distribución acumulada caso continuo

La función de distribución acumulada (*fda*) denotada por `$F(x)$`, para una variable aleatoria continua `$X$` con distribución de probabilidad `$f(x)$` es de la forma 
`\begin{align*}
F(x)=P(X\leq x)=\int_{-\infty}^x f(t) dt \quad \quad
\end{align*}`

para cualquier `$x$`, `$F(x)$` es el área izquierda bajo la curva de densidad.

## Esperanza matemática caso continuo

Si `$x$` es una variable aleatoria con *fdp* `$f(x)$`, entonces la media o valor esperado de la variable aleatoria se denota por `$\mathbb{E}(X)$` o `$\mu$` está dada por
`\begin{align*}
\mathbb{E}(X)=\int_{-\infty}^\infty xf(x) dx
\end{align*}`

## Varianza caso continuo
Sea `$X$` una variable aleatoria con *fdp* `$f(x)$`, entonces si `$m(X) = (X - \mathbb{E}(X))^2$`, se tendrá que la varianza de `$X$` que se denota `$Var(X)$` o `$\sigma^2$` estará dada por
`\begin{align*}
Var(X) = \mathbb{E}\left[\left(X-\mathbb{E}(X)\right)^2\right]=\int_{-\infty}^\infty(x-\mathbb{E}(X))^2f(x) dx
\end{align*}`

Similar al caso discreto, se puede demostrar a partir de la ecuación anterior, que una alternativa para el cálculo de la `$Var(X)$` es de la forma

`\begin{align*}
Var(X) = \mathbb{E}(X^2) - \mathbb{E}(X)^2
\end{align*}`

además, la raíz cuadrada de la varianza de `$X$` se llama desviación estándar de `$X$`, se denota por `$Sd(X)$` o `$\sigma$` y se define como
`\begin{align*}
Sd(X) = \sqrt{Var(X)}
\end{align*}`