---
layout: post
title: "Trabajo"
main-class: 'practica'
permalink: /MuestreoySeriesdeTiempo/MyST:title.html
tags:

introduction: |
  Indicaciones trabajo muestreo
  
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../MuestreoySeriesdeTiempo/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../MuestreoySeriesdeTiempo/images/", "Trabajo"),
               cache.path = "../../MuestreoySeriesdeTiempo/cache/",
               cache = FALSE)

```

# Indicaciones trabajo muestreo
1. Planteamiento de los objetivos generales y específicos de la encuesta (Por qué, para qué y cómo)
2. Determinar el marco de muestreo (Selección de la población objetivo)
3. Métodos de recolección de información (Explicar los métodos que se usarán para la recolección de la información)
4. Instrumento de medición (Diseño de la encuesta y el por qué de las preguntas)
5. Prueba piloto (Selección de muestra prueba piloto) 
6. Análisis de resultados prueba piloto y cálculo de tamaño muestral prueba final
7. Redacción del cuestionario definitivo (Correcciones para la encuesta final)
8. Aplicación encuesta final y análisis de resultados
9. Conclusiones (si se alcanzó o no, el objetivo planteado, cuales son los retos o recomendaciones para próximos trabajos)
