---
layout: post
title: "Clase 04"
main-class: 'clase'
permalink: /MuestreoySeriesdeTiempo/MyST:title.html
tags:

introduction: |
  Modelo no-paramétricos de series de tiempo. <br/>
  Series estacionarias en media: <br/>
  - Promedios simples. <br/>
  - Promedios móviles unilaterales y bilaterales. <br/>
  - Suavizamiento exponencial simple.
header-includes:
   - \usepackage{amsmath,amssymb,amsthm,amsfonts}
   - \usepackage[sectionbib]{natbib}
   - \usepackage[hidelinks]{hyperref}
output:
  md_document:
    variant: markdown_strict+backtick_code_blocks+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash
    preserve_yaml: TRUE
always_allow_html: yes   
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../../MuestreoySeriesdeTiempo/_posts/", output_format = "all"  ) })
bibliography: "../../referencias.bib"
csl: "../../apa.csl"
link-citations: yes
---

```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
## Global options
opts_chunk$set(echo=TRUE,
               cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE,
               fig.path = paste0("../../MuestreoySeriesdeTiempo/images/", "Clase04"),
               cache.path = "../../MuestreoySeriesdeTiempo/cache/",
               cache = FALSE)
```

## Introducción al modelamiento de series de tiempo
Cómo se ha mencionado hasta ahora, uno de los aspecto más importantes en las series de tiempo, recae en la adecuada selección del modelo que se va a emplear, debido a que éste será el que refleje la estructura de la serie, y a su vez, permitirá la realización de pronósticos futuros.

Entre las alternativas para el modelamiento de una serie de tiempo, se presentan modelos lineales o no lineales, los cuales se emplean dependiendo de la estructura que tenga la serie de tiempo respecto a sus observaciones pasadas.

## Métodos no-paramétricos
Como su nombre lo índica, los métodos no-paramétricos son aquellos que no poseen una estructura paramétrica, si no que sus estimaciones son basadas en algoritmos que varían en cada periodo `$t$`, sin asumir una forma paramétrica específica, y además, a diferencia de los métodos paramétricos, éstos no requieren de supuestos estadísticos para su aplicación, ni modelamiento global, lo cual en muchos casos pueden ser muy restrictivo.

Es de anotar que se debe tener precaución a la hora de aplicar métodos no-paramétricos, debido a que no todos están diseñados para ser aplicados sin importar las componentes de la serie, y por tanto, dependiendo de la o las componentes de la serie de tiempo que hayan sido identificadas, se debe seleccionar el método no-paramétrico que más conveniente, a saber

* **Series estacionarias en media:** Promedios simples, Promedios móviles - Suavizamiento exponencial simple
* **Series con tendencia:** Promedios móviles dobles - Suavizamiento exponencial de Holt - Suavizamiento exponencial de Brown
* **Series estacionales:** Suavizamiento exponencial de Holt-Winters aditivo - Suavizamiento exponencial de Holt-Winters multiplicativo

## Filtros lineales y suavizadores
Suavizar o filtrar una serie temporal, es similar a la idea de aplicar filtros a la música a través de un amplificador. Podemos amplificar ciertos sonidos o podemos suprimir ciertos sonidos, similarmente, también podemos suprimir (eliminar) ciertas características de una serie de tiempo como la estacionalidad, para poder modelar la tendencia de la misma. Una vez que hemos construido un modelo adecuado para la serie desestacionalizada, podemos agregar nuevamente la componente estacional a los pronósticos de nuestra serie.

Por tanto, el empleo de los filtros y suavizaciones, ayuda a determinar la tendencia reduciendo las fluctuaciones locales, y además, pueden usarse como estimadores de la tendencia cuando no es posible describirla mediante ecuaciones paramétricas simples.

Entonces, un filtro lineal puede definirse como un operador que transforma una serie `$Y_t$`, a otra serie `$\bar{Y}_t$`, para `$t = 1,2, \ldots, T$` mediante la formula
`\begin{align*}
\bar{Y}_t=\sum_{i=-k}^{k}w_iY_{t-i}
\end{align*}`

para `$t=k+1,k+2, \ldots, T-k$`, donde `$i=0,\pm1,\pm2,\ldots, \pm k$` es el ancho de la ventana y los coeficientes `$w_i$` son un conjunto de pesos o ponderaciones, tal que `$\sum_{i=-k}^{k}|w_i|<\infty$`. Además, en situaciones en los cuales se desea determinar la tendencia y reducir las fluctuaciones locales, se pueden restringir los pesos `$w_i$` de la forma `$\sum_{i=-k}^{k}w_i=1$`.

## Series estacionarias en media
### Promedios simples
Los promedios simples se basan en el hecho de que todos los `$w_i$` poseen la misma ponderación, la cual es igual a `$w_i=\frac{1}{t}$`, y a partir de éstas ponderaciones, se obtiene una ecuación de la forma
`\begin{align*}
PS_{t}=\frac{1}{t}\sum_{i=1}^{t}{Y_{i}}
\end{align*}`

para `$i=1,2,\ldots,t$`, con `$t=1,2,\ldots,T$` y siendo `$T$` el total de observaciones históricas de la serie de tiempo. Es de anotar que, los promedios simples son de hecho igual a la media de todo el conjunto de observaciones hasta `$t$`, y que su valor se actualiza periodicamente a medida que se van agregando nuevas observaciones al cojunto de datos. Dado que esta medida es el promedio de todo el conjunto de datos históricos de la serie, esta estimación no tendrá cambios significativos cuando se ingresan nuevas observaciones.

@Hanke2010[, p. 111], señalan que, el método de promedios simples es una técnica adecuada cuando los factores que producen la serie que se va a pronosticar se han estabilizado y el ambiente en el cual se encuentra la serie generalmente permanece sin cambios, es decir, es adecuada cuando se posea una serie estacionaria en media, con variabilidad pequeña y sin ningún tipo de tendencia.

Adicionalmente, en los promedios simples, el ajuste de las observaciones se hace de la forma
`\begin{align*}
\hat{Y}_{t+1}=PS_t
\end{align*}`

mientras que, el ajuste de pronósticos se hace de la forma
`\begin{align*}
\hat{Y}_{T+h}=PS_{T+h-1}
\end{align*}`

siendo `$h$` el número de periodos a pronosticar.

### Promedios móviles simples
Es uno de los filtros más sencillos de emplear, y se basa en el cálculo del promedio de las últimas `$k$` observaciones (promedios móviles unilaterales (PMU)), o las `$k$` observaciones más cercanas al dato de interés (promedios móviles bilaterales (PMB)), y por tanto, el suavizamiento del conjunto de observaciones dependerá de la selección del **ancho de ventana** de orden `$k$` que se realice, en donde, debe tenerse en cuenta que, entre mayor sea el valor de `$k$`, mayor será el suavizamiento resultante.

Para un ancho de ventana de orden `$k$`, se tendrá que en el caso de promedio móvil unilateral, las ponderaciones `$w_i$` serán de la forma `$w_i=\frac{1}{k}$`, y en consecuencia, el estadístico estará dado por
`\begin{align*}
PMU_{t}=\frac{1}{k}\sum_{i=0}^{k-1}Y_{t-i}
\end{align*}`

<!-- Puede realizarse mediante la librerías TTR con la función SMA -->

para `$t=k,k+1,k+2, \ldots, T$`, con `$i=0,1,\ldots, k-1$` y `$k>0$`. Mientras que, en el caso de media móvil bilateral las ponderaciones serán de la forma `$w_i=\frac{1}{2m+1}$`,  y por tanto, el estadístico se define como
`\begin{align*}
PMB_{t}=\frac{1}{2k+1}\sum_{i=-k}^{k}Y_{t-i}
\end{align*}`

para `$t=k+1,k+2, \ldots, T-k$`, con `$i=0,\pm 1,\pm 2,\ldots,\pm k$` y `$k>0$`.

@Hanke2010[, pp. 116-117], señalan que, los analistas deben usar su criterio en la determinación del orden en el cual se basa el promedio móvil, ya que, entre menor sea el orden, mayor es el peso que se asigna a los periodos más recientes, mientras que, entre mayor es el orden, menor es el peso que se asigna a los periodos más recientes.

Por tanto, es más deseable un **orden pequeño** cuando existen cambios repentinos en el nivel de la serie, ya que un número pequeño pone mayor peso a la historia reciente, lo cual facilita que los pronósticos alcancen más rápidamente el nivel real, y por el contraio, es más deseable un **orden grande** cuando hay fluctuaciones amplias y poco frecuentes en las series.

Es de anotar que en los promedios móviles simples, el ajuste de las observaciones se hace de la forma
`\begin{align*}
\hat{Y}_{t+1}=
\begin{cases}
PMU_t & \text{ en el caso de promedios móviles unilaterales} \\
PMB_t & \text{ en el caso de promedios móviles bilaterales}
\end{cases}
\end{align*}`

mientras que, el ajuste de pronósticos se hace de la forma

`\begin{align*}
\hat{Y}_{T+h}=
\begin{cases}
PMU_{T+h-1} & \text{ en el caso de promedios móviles unilaterales} \\
PMB_{T+h-1} & \text{ en el caso de promedios móviles bilaterales}
\end{cases}
\end{align*}`

siendo `$h$` el número de periodos a pronosticar. Adicionalmente, en el caso unilateral, si `$k = 1$` se tendrá una situación conocida como *Modelos Informales*, en donde, el pronóstico de una observación `$t+1$` depende solamente de la observación `$t$`, la cual es la observación inmediatamente anterior.

### Suavización exponencial simple
Similar al método de los promedios simples, la suavización exponencial simple emplea todas las observaciones históricas de la variable de interés, pero con la diferencia de que, en lugar de darle la misma ponderación a todas las observaciones, ésta da pesos exponenciales a todos los valores previos observados, siendo las observaciones más recientes las que posean la mayor ponderacion. 

El parámetro de suavización se denota por `$\alpha$`, y estará dado por un valor que se encuentre entre 0 y 1, es decir, `$0<\alpha<1$`. Entonces, el objetivo será dar una ponderación de `$\alpha$` a la observación más reciente, una ponderación de `$\alpha(1-\alpha)$` a la siguiente observación más reciente, una ponderación de `$\alpha(1-\alpha)^2$` a la observación de dos rezagos en el pasado, `$\alpha(1-\alpha)^3$` a la observación de tres rezagos en el pasado y así sucesivamente.

En general la ecuación de suavizamiento exponencial puede ser escrita como
`\begin{align}\label{eq:1}
\hat{Y}_{t+1}=\alpha Y_{t} + \alpha(1-\alpha) Y_{t-1} + \alpha(1-\alpha)^2 Y_{t-2} + \alpha(1-\alpha)^3 Y_{t-3} + \ldots 
\end{align}`

Con el fin de simplificar la formula anterior, observemos que
`\begin{align*}
\hat{Y}_{t}=\alpha Y_{t-1} + \alpha(1-\alpha) Y_{t-2} + \alpha(1-\alpha)^2 Y_{t-3} + \alpha(1-\alpha)^3 Y_{t-4} + \ldots
\end{align*}`

lo cual es equivalente a
`\begin{align} \label{eq:2}
(1-\alpha)\hat{Y}_{t}=\alpha(1-\alpha) Y_{t-1} + \alpha(1-\alpha)^2 Y_{t-2} + \alpha(1-\alpha)^3 Y_{t-3} + \alpha(1-\alpha)^4 Y_{t-4} + \ldots 
\end{align}`

<!-- Corregir la estimación!!! a partir de lo visto en la clase 05 de suavización doble de brown -->
y por tanto, al reemplazar (\\ref{eq:2}) en (\\ref{eq:1}), se obtiene una expresión más sencilla para el cálculo del método de suavizamiento, la cual está dada por
`\begin{align*}
SES_{t+1} = \hat{Y}_{t+1}=\alpha Y_{t} + (1-\alpha)\hat{Y}_{t}
\end{align*}`

o equivalentemente
`\begin{align*}
SES_{t+1} = \hat{Y}_{t+1}=\hat{Y}_{t}+\alpha(Y_{t}-\hat{Y}_{t})
\end{align*}`

@Hanke2010[, p. 120] señalan que, el valor de `$\alpha$` determina el grado de influencia de las observaciones pasadas sobre el sobre el valor pronósticados, y en consecuencia, entre más cercano se encuentre el parámetro `$\alpha$` de 1, se tendrá que el valor pronosticado tendrá una mayor similaridad al valor observado más reciente, y por tanto, no se recomienda usar este método debido a que la serie resultante será similar a la serie original. 

Por el contrario, entre más cercano se encuentre el parámetro `$\alpha$` de 0, se tendrá que las observaciones más recientes tendrán menor efecto sobre el valor pronosticado, y por tanto, la serie resultante será más suave que la serie original.

<!-- Puede realizarse mediante la librerías TTR con la función EMA -->
<!-- R usa 2/(n+1) o 1/n, siendo n el total de periodos que quiere promediar inicialmente, alternativamente se puede emplear un criterio para minimizar el MSE-->

Es de anotar que en la suavización exponencial simples, **el ajuste de la primera observación** se puede hacer de diferentes formas, entre las cuales destaca

* `$\hat{Y}_{k} = Y_{k-1}$`
* `$\hat{Y}_{k} = \frac{1}{k}\sum_{t=1}^{k}Y_{t}$`

siendo `$k>1$` el orden desde el cuál se desea comenzar la suavización exponencial.

Para ajustar las demás observaciones, se hace de la forma
`\begin{align*}
\hat{Y}_{t+1} = \hat{Y}_{t}+\alpha(Y_{t}-\hat{Y}_{t})
\end{align*}`

mientras que, el ajuste de pronósticos se hace de la forma
`\begin{align*}
\hat{Y}_{T+h} = \hat{Y}_{T+h-1}+\alpha(Y_{T+h-1}-\hat{Y}_{T+h-1})
\end{align*}`

siendo `$h$` el número de periodos a pronosticar.

## Bibliografía


